import Head from "next/head";
import PDFViewer from "./PDFViewer";
import TestPage from "./testPage";
import { useRouter } from "next/router";
import React, { useState, useEffect } from "react";

export default function Home() {
  const Router = useRouter();
  const [sitePath, setSitePath] = useState(null);
  const [data, setData] = useState(null);

  useEffect(() => {
    let { site_path, data } = Router.query;
    setSitePath(site_path);
    setData(data);
  }, [Router]);

  return (
    <>
      <Head>
        <title>DOP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{sitePath == "pdfview" && <PDFViewer data={data} />}</main>
      <main>{sitePath == "test" && <TestPage />}</main>
    </>
  );
}
